// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmos/shielded/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryPublicBalanceRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryPublicBalanceRequest) Reset()         { *m = QueryPublicBalanceRequest{} }
func (m *QueryPublicBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPublicBalanceRequest) ProtoMessage()    {}
func (*QueryPublicBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{0}
}
func (m *QueryPublicBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublicBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublicBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublicBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublicBalanceRequest.Merge(m, src)
}
func (m *QueryPublicBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublicBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublicBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublicBalanceRequest proto.InternalMessageInfo

func (m *QueryPublicBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryPublicBalanceResponse struct {
	Balance uint64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (m *QueryPublicBalanceResponse) Reset()         { *m = QueryPublicBalanceResponse{} }
func (m *QueryPublicBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPublicBalanceResponse) ProtoMessage()    {}
func (*QueryPublicBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{1}
}
func (m *QueryPublicBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublicBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublicBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublicBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublicBalanceResponse.Merge(m, src)
}
func (m *QueryPublicBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublicBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublicBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublicBalanceResponse proto.InternalMessageInfo

func (m *QueryPublicBalanceResponse) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type QueryPrivateBalanceRequest struct {
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (m *QueryPrivateBalanceRequest) Reset()         { *m = QueryPrivateBalanceRequest{} }
func (m *QueryPrivateBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPrivateBalanceRequest) ProtoMessage()    {}
func (*QueryPrivateBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{2}
}
func (m *QueryPrivateBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPrivateBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPrivateBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPrivateBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPrivateBalanceRequest.Merge(m, src)
}
func (m *QueryPrivateBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPrivateBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPrivateBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPrivateBalanceRequest proto.InternalMessageInfo

func (m *QueryPrivateBalanceRequest) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

type QueryPrivateBalanceResponse struct {
	TotalBalance uint64 `protobuf:"varint,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
}

func (m *QueryPrivateBalanceResponse) Reset()         { *m = QueryPrivateBalanceResponse{} }
func (m *QueryPrivateBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPrivateBalanceResponse) ProtoMessage()    {}
func (*QueryPrivateBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{3}
}
func (m *QueryPrivateBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPrivateBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPrivateBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPrivateBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPrivateBalanceResponse.Merge(m, src)
}
func (m *QueryPrivateBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPrivateBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPrivateBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPrivateBalanceResponse proto.InternalMessageInfo

func (m *QueryPrivateBalanceResponse) GetTotalBalance() uint64 {
	if m != nil {
		return m.TotalBalance
	}
	return 0
}

type QueryCommitmentsRequest struct {
	PoolId     uint64             `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCommitmentsRequest) Reset()         { *m = QueryCommitmentsRequest{} }
func (m *QueryCommitmentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentsRequest) ProtoMessage()    {}
func (*QueryCommitmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{4}
}
func (m *QueryCommitmentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentsRequest.Merge(m, src)
}
func (m *QueryCommitmentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentsRequest proto.InternalMessageInfo

func (m *QueryCommitmentsRequest) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *QueryCommitmentsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCommitmentsResponse struct {
	Commitments [][]byte            `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCommitmentsResponse) Reset()         { *m = QueryCommitmentsResponse{} }
func (m *QueryCommitmentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentsResponse) ProtoMessage()    {}
func (*QueryCommitmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{5}
}
func (m *QueryCommitmentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentsResponse.Merge(m, src)
}
func (m *QueryCommitmentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentsResponse proto.InternalMessageInfo

func (m *QueryCommitmentsResponse) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

func (m *QueryCommitmentsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMerkleRootRequest struct {
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
}

func (m *QueryMerkleRootRequest) Reset()         { *m = QueryMerkleRootRequest{} }
func (m *QueryMerkleRootRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMerkleRootRequest) ProtoMessage()    {}
func (*QueryMerkleRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{6}
}
func (m *QueryMerkleRootRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerkleRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerkleRootRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerkleRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerkleRootRequest.Merge(m, src)
}
func (m *QueryMerkleRootRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerkleRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerkleRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerkleRootRequest proto.InternalMessageInfo

func (m *QueryMerkleRootRequest) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

type QueryMerkleRootResponse struct {
	MerkleRoot []byte `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
}

func (m *QueryMerkleRootResponse) Reset()         { *m = QueryMerkleRootResponse{} }
func (m *QueryMerkleRootResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMerkleRootResponse) ProtoMessage()    {}
func (*QueryMerkleRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_747477e3065399e4, []int{7}
}
func (m *QueryMerkleRootResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerkleRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerkleRootResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerkleRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerkleRootResponse.Merge(m, src)
}
func (m *QueryMerkleRootResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerkleRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerkleRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerkleRootResponse proto.InternalMessageInfo

func (m *QueryMerkleRootResponse) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPublicBalanceRequest)(nil), "evmos.shielded.v1.QueryPublicBalanceRequest")
	proto.RegisterType((*QueryPublicBalanceResponse)(nil), "evmos.shielded.v1.QueryPublicBalanceResponse")
	proto.RegisterType((*QueryPrivateBalanceRequest)(nil), "evmos.shielded.v1.QueryPrivateBalanceRequest")
	proto.RegisterType((*QueryPrivateBalanceResponse)(nil), "evmos.shielded.v1.QueryPrivateBalanceResponse")
	proto.RegisterType((*QueryCommitmentsRequest)(nil), "evmos.shielded.v1.QueryCommitmentsRequest")
	proto.RegisterType((*QueryCommitmentsResponse)(nil), "evmos.shielded.v1.QueryCommitmentsResponse")
	proto.RegisterType((*QueryMerkleRootRequest)(nil), "evmos.shielded.v1.QueryMerkleRootRequest")
	proto.RegisterType((*QueryMerkleRootResponse)(nil), "evmos.shielded.v1.QueryMerkleRootResponse")
}

func init() { proto.RegisterFile("evmos/shielded/v1/query.proto", fileDescriptor_747477e3065399e4) }

var fileDescriptor_747477e3065399e4 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x31, 0x6f, 0xd3, 0x4e,
	0x18, 0xc6, 0x7b, 0xfd, 0xff, 0xdb, 0x8a, 0x4b, 0x8a, 0xc4, 0x09, 0xd1, 0x60, 0xc0, 0x44, 0x46,
	0x82, 0x90, 0xb4, 0xe7, 0x26, 0xa5, 0x0c, 0x8c, 0x41, 0x80, 0x18, 0x90, 0x8a, 0x47, 0x96, 0xe8,
	0x1c, 0x9f, 0x5c, 0x0b, 0xdb, 0xe7, 0xfa, 0x2e, 0x56, 0x0b, 0xea, 0x82, 0x04, 0x33, 0x12, 0x42,
	0x62, 0x65, 0xe0, 0xbb, 0x30, 0x56, 0x62, 0x61, 0x44, 0x09, 0x1f, 0x04, 0xf9, 0x7c, 0xc6, 0x0e,
	0x76, 0x94, 0x2c, 0x51, 0xee, 0xde, 0xf7, 0x79, 0x9f, 0x5f, 0x5e, 0x3f, 0x31, 0xbc, 0x45, 0x93,
	0x80, 0x71, 0x93, 0x1f, 0x7b, 0xd4, 0x77, 0xa8, 0x63, 0x26, 0x7d, 0xf3, 0x64, 0x42, 0xe3, 0x33,
	0x1c, 0xc5, 0x4c, 0x30, 0x74, 0x45, 0x96, 0x71, 0x5e, 0xc6, 0x49, 0x5f, 0xbb, 0xea, 0x32, 0x97,
	0xc9, 0xaa, 0x99, 0x7e, 0xcb, 0x1a, 0xb5, 0x9b, 0x2e, 0x63, 0xae, 0x4f, 0x4d, 0x12, 0x79, 0x26,
	0x09, 0x43, 0x26, 0x88, 0xf0, 0x58, 0xc8, 0x55, 0xb5, 0x3b, 0x66, 0x3c, 0xb5, 0xb1, 0x09, 0xa7,
	0xd9, 0x7c, 0x33, 0xe9, 0xdb, 0x54, 0x90, 0xbe, 0x19, 0x11, 0xd7, 0x0b, 0x65, 0xb3, 0xea, 0xd5,
	0xaa, 0x44, 0xe2, 0x34, 0xab, 0x19, 0x87, 0xf0, 0xfa, 0xcb, 0x54, 0x7d, 0x34, 0xb1, 0x7d, 0x6f,
	0x3c, 0x24, 0x3e, 0x09, 0xc7, 0xd4, 0xa2, 0x27, 0x13, 0xca, 0x05, 0x6a, 0xc1, 0x2d, 0xe2, 0x38,
	0x31, 0xe5, 0xbc, 0x05, 0xda, 0xa0, 0x73, 0xc9, 0xca, 0x8f, 0xc6, 0x43, 0xa8, 0xd5, 0xc9, 0x78,
	0xc4, 0x42, 0x4e, 0x53, 0x9d, 0x9d, 0x5d, 0x49, 0xdd, 0xff, 0x56, 0x7e, 0x34, 0x0e, 0x73, 0x5d,
	0xec, 0x25, 0x44, 0xd0, 0x7f, 0xfc, 0x76, 0xe0, 0x56, 0xc4, 0x98, 0x3f, 0xf2, 0x1c, 0xa5, 0xdb,
	0x4c, 0x8f, 0xcf, 0x1d, 0x63, 0x08, 0x6f, 0xd4, 0xca, 0x94, 0xdf, 0x1d, 0xb8, 0x2d, 0x98, 0x20,
	0xfe, 0x68, 0xde, 0xb5, 0x29, 0x2f, 0x55, 0xb3, 0xf1, 0x06, 0xee, 0xc8, 0x19, 0x8f, 0x59, 0x10,
	0x78, 0x22, 0xa0, 0xa1, 0xe0, 0xcb, 0x7c, 0xd1, 0x53, 0x08, 0x8b, 0x6d, 0xb6, 0xd6, 0xdb, 0xa0,
	0xd3, 0x18, 0xdc, 0xc5, 0xd9, 0xea, 0x71, 0xba, 0x7a, 0x9c, 0x3d, 0x5a, 0xb5, 0x7a, 0x7c, 0x44,
	0xdc, 0xfc, 0xc7, 0x58, 0x25, 0xa5, 0xf1, 0x1e, 0xc0, 0x56, 0xd5, 0x5c, 0xd1, 0xb7, 0x61, 0x63,
	0x5c, 0x5c, 0xb7, 0x40, 0xfb, 0xbf, 0x4e, 0xd3, 0x2a, 0x5f, 0xa1, 0x67, 0x35, 0x18, 0xf7, 0x96,
	0x62, 0x64, 0xe3, 0xe7, 0x38, 0xfa, 0xf0, 0x9a, 0xc4, 0x78, 0x41, 0xe3, 0xd7, 0x3e, 0xb5, 0x18,
	0x13, 0x4b, 0x57, 0xff, 0x48, 0xad, 0xad, 0x2c, 0x51, 0xe0, 0xb7, 0x61, 0x23, 0x90, 0xb7, 0xa3,
	0x98, 0x31, 0x21, 0x75, 0x4d, 0x0b, 0x06, 0x7f, 0x1b, 0x07, 0x1f, 0x36, 0xe0, 0x86, 0x14, 0xa3,
	0xaf, 0x00, 0x6e, 0xcf, 0x65, 0x05, 0xed, 0xe2, 0xca, 0x1f, 0x01, 0x2f, 0x4c, 0xa2, 0xb6, 0xb7,
	0x62, 0x77, 0x46, 0x66, 0x1c, 0xbc, 0xfb, 0xf1, 0xfb, 0xd3, 0xfa, 0x1e, 0xea, 0x99, 0xd5, 0xe8,
	0x47, 0x52, 0x91, 0x47, 0xc5, 0x7c, 0xab, 0x22, 0x7d, 0x8e, 0xbe, 0x01, 0x78, 0x79, 0x3e, 0x60,
	0x68, 0xb1, 0x6d, 0x5d, 0x7e, 0x35, 0xbc, 0x6a, 0xbb, 0xc2, 0x7c, 0x20, 0x31, 0x31, 0xda, 0xad,
	0xc3, 0xcc, 0x24, 0x05, 0xa7, 0x7a, 0x3c, 0xe7, 0xe8, 0x0b, 0x80, 0x8d, 0x52, 0x8e, 0x50, 0x77,
	0x91, 0x6b, 0x35, 0xe9, 0x5a, 0x6f, 0xa5, 0x5e, 0x85, 0xb7, 0x2f, 0xf1, 0xba, 0xa8, 0x53, 0x83,
	0x57, 0x8a, 0x67, 0x09, 0xed, 0x33, 0x80, 0xb0, 0x08, 0x0a, 0xba, 0xbf, 0xc8, 0xad, 0x92, 0x3f,
	0xad, 0xbb, 0x4a, 0xeb, 0x0a, 0x5c, 0xa5, 0x40, 0x16, 0x5c, 0xc3, 0x27, 0xdf, 0xa7, 0x3a, 0xb8,
	0x98, 0xea, 0xe0, 0xd7, 0x54, 0x07, 0x1f, 0x67, 0xfa, 0xda, 0xc5, 0x4c, 0x5f, 0xfb, 0x39, 0xd3,
	0xd7, 0x5e, 0xf5, 0x5c, 0x4f, 0x1c, 0x4f, 0x6c, 0x3c, 0x66, 0x81, 0x9a, 0x96, 0x7d, 0x26, 0x83,
	0x7d, 0xf3, 0xb4, 0x98, 0x2c, 0xce, 0x22, 0xca, 0xed, 0x4d, 0xf9, 0xce, 0x3c, 0xf8, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0x5c, 0x6f, 0xbf, 0xe3, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// PublicBalance queries the public balance of an account
	PublicBalance(ctx context.Context, in *QueryPublicBalanceRequest, opts ...grpc.CallOption) (*QueryPublicBalanceResponse, error)
	// PrivateBalance queries the total private balance in a pool
	PrivateBalance(ctx context.Context, in *QueryPrivateBalanceRequest, opts ...grpc.CallOption) (*QueryPrivateBalanceResponse, error)
	// Commitments queries all unspent commitments in a pool
	Commitments(ctx context.Context, in *QueryCommitmentsRequest, opts ...grpc.CallOption) (*QueryCommitmentsResponse, error)
	// MerkleRoot queries the current Merkle root of a pool
	MerkleRoot(ctx context.Context, in *QueryMerkleRootRequest, opts ...grpc.CallOption) (*QueryMerkleRootResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PublicBalance(ctx context.Context, in *QueryPublicBalanceRequest, opts ...grpc.CallOption) (*QueryPublicBalanceResponse, error) {
	out := new(QueryPublicBalanceResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Query/PublicBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PrivateBalance(ctx context.Context, in *QueryPrivateBalanceRequest, opts ...grpc.CallOption) (*QueryPrivateBalanceResponse, error) {
	out := new(QueryPrivateBalanceResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Query/PrivateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Commitments(ctx context.Context, in *QueryCommitmentsRequest, opts ...grpc.CallOption) (*QueryCommitmentsResponse, error) {
	out := new(QueryCommitmentsResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Query/Commitments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MerkleRoot(ctx context.Context, in *QueryMerkleRootRequest, opts ...grpc.CallOption) (*QueryMerkleRootResponse, error) {
	out := new(QueryMerkleRootResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Query/MerkleRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// PublicBalance queries the public balance of an account
	PublicBalance(context.Context, *QueryPublicBalanceRequest) (*QueryPublicBalanceResponse, error)
	// PrivateBalance queries the total private balance in a pool
	PrivateBalance(context.Context, *QueryPrivateBalanceRequest) (*QueryPrivateBalanceResponse, error)
	// Commitments queries all unspent commitments in a pool
	Commitments(context.Context, *QueryCommitmentsRequest) (*QueryCommitmentsResponse, error)
	// MerkleRoot queries the current Merkle root of a pool
	MerkleRoot(context.Context, *QueryMerkleRootRequest) (*QueryMerkleRootResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PublicBalance(ctx context.Context, req *QueryPublicBalanceRequest) (*QueryPublicBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicBalance not implemented")
}
func (*UnimplementedQueryServer) PrivateBalance(ctx context.Context, req *QueryPrivateBalanceRequest) (*QueryPrivateBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateBalance not implemented")
}
func (*UnimplementedQueryServer) Commitments(ctx context.Context, req *QueryCommitmentsRequest) (*QueryCommitmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commitments not implemented")
}
func (*UnimplementedQueryServer) MerkleRoot(ctx context.Context, req *QueryMerkleRootRequest) (*QueryMerkleRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerkleRoot not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PublicBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublicBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PublicBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Query/PublicBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PublicBalance(ctx, req.(*QueryPublicBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PrivateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPrivateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PrivateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Query/PrivateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PrivateBalance(ctx, req.(*QueryPrivateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Commitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Commitments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Query/Commitments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Commitments(ctx, req.(*QueryCommitmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Query/MerkleRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MerkleRoot(ctx, req.(*QueryMerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.shielded.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicBalance",
			Handler:    _Query_PublicBalance_Handler,
		},
		{
			MethodName: "PrivateBalance",
			Handler:    _Query_PrivateBalance_Handler,
		},
		{
			MethodName: "Commitments",
			Handler:    _Query_Commitments_Handler,
		},
		{
			MethodName: "MerkleRoot",
			Handler:    _Query_MerkleRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmos/shielded/v1/query.proto",
}

func (m *QueryPublicBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublicBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublicBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPublicBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublicBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublicBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Balance != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPrivateBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPrivateBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPrivateBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPrivateBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPrivateBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPrivateBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalBalance != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalBalance))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommitmentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PoolId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommitmentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Commitments) > 0 {
		for iNdEx := len(m.Commitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Commitments[iNdEx])
			copy(dAtA[i:], m.Commitments[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Commitments[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerkleRootRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerkleRootRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerkleRootRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerkleRootResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerkleRootResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerkleRootResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPublicBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPublicBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Balance != 0 {
		n += 1 + sovQuery(uint64(m.Balance))
	}
	return n
}

func (m *QueryPrivateBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovQuery(uint64(m.PoolId))
	}
	return n
}

func (m *QueryPrivateBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalBalance != 0 {
		n += 1 + sovQuery(uint64(m.TotalBalance))
	}
	return n
}

func (m *QueryCommitmentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovQuery(uint64(m.PoolId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCommitmentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Commitments) > 0 {
		for _, b := range m.Commitments {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerkleRootRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovQuery(uint64(m.PoolId))
	}
	return n
}

func (m *QueryMerkleRootResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPublicBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublicBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublicBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPublicBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublicBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublicBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPrivateBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPrivateBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPrivateBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPrivateBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPrivateBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPrivateBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBalance", wireType)
			}
			m.TotalBalance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalBalance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommitmentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommitmentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitments = append(m.Commitments, make([]byte, postIndex-iNdEx))
			copy(m.Commitments[len(m.Commitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerkleRootRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerkleRootRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerkleRootRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerkleRootResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerkleRootResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerkleRootResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
