// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmos/shielded/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgDepositToShielded deposits tokens to create a shielded commitment
type MsgDepositToShielded struct {
	Sender     string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId     uint64 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Amount     uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Commitment []byte `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	Proof      []byte `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *MsgDepositToShielded) Reset()         { *m = MsgDepositToShielded{} }
func (m *MsgDepositToShielded) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToShielded) ProtoMessage()    {}
func (*MsgDepositToShielded) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{0}
}
func (m *MsgDepositToShielded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToShielded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToShielded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToShielded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToShielded.Merge(m, src)
}
func (m *MsgDepositToShielded) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToShielded) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToShielded.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToShielded proto.InternalMessageInfo

func (m *MsgDepositToShielded) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgDepositToShielded) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *MsgDepositToShielded) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgDepositToShielded) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *MsgDepositToShielded) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type MsgDepositToShieldedResponse struct {
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *MsgDepositToShieldedResponse) Reset()         { *m = MsgDepositToShieldedResponse{} }
func (m *MsgDepositToShieldedResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositToShieldedResponse) ProtoMessage()    {}
func (*MsgDepositToShieldedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{1}
}
func (m *MsgDepositToShieldedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDepositToShieldedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDepositToShieldedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDepositToShieldedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositToShieldedResponse.Merge(m, src)
}
func (m *MsgDepositToShieldedResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDepositToShieldedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositToShieldedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositToShieldedResponse proto.InternalMessageInfo

func (m *MsgDepositToShieldedResponse) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

// MsgPrivateSend sends tokens privately without revealing amount
type MsgPrivateSend struct {
	Sender              string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId              uint64 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Nullifier           []byte `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	SenderIdentity      []byte `protobuf:"bytes,4,opt,name=sender_identity,json=senderIdentity,proto3" json:"sender_identity,omitempty"`
	RecipientCommitment []byte `protobuf:"bytes,5,opt,name=recipient_commitment,json=recipientCommitment,proto3" json:"recipient_commitment,omitempty"`
	ChangeCommitment    []byte `protobuf:"bytes,6,opt,name=change_commitment,json=changeCommitment,proto3" json:"change_commitment,omitempty"`
	MerkleRoot          []byte `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Proof               []byte `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
	MerklePathSize      uint32 `protobuf:"varint,9,opt,name=merkle_path_size,json=merklePathSize,proto3" json:"merkle_path_size,omitempty"`
}

func (m *MsgPrivateSend) Reset()         { *m = MsgPrivateSend{} }
func (m *MsgPrivateSend) String() string { return proto.CompactTextString(m) }
func (*MsgPrivateSend) ProtoMessage()    {}
func (*MsgPrivateSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{2}
}
func (m *MsgPrivateSend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPrivateSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPrivateSend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPrivateSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPrivateSend.Merge(m, src)
}
func (m *MsgPrivateSend) XXX_Size() int {
	return m.Size()
}
func (m *MsgPrivateSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPrivateSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPrivateSend proto.InternalMessageInfo

func (m *MsgPrivateSend) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgPrivateSend) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *MsgPrivateSend) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *MsgPrivateSend) GetSenderIdentity() []byte {
	if m != nil {
		return m.SenderIdentity
	}
	return nil
}

func (m *MsgPrivateSend) GetRecipientCommitment() []byte {
	if m != nil {
		return m.RecipientCommitment
	}
	return nil
}

func (m *MsgPrivateSend) GetChangeCommitment() []byte {
	if m != nil {
		return m.ChangeCommitment
	}
	return nil
}

func (m *MsgPrivateSend) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *MsgPrivateSend) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgPrivateSend) GetMerklePathSize() uint32 {
	if m != nil {
		return m.MerklePathSize
	}
	return 0
}

type MsgPrivateSendResponse struct {
	RecipientCommitment []byte `protobuf:"bytes,1,opt,name=recipient_commitment,json=recipientCommitment,proto3" json:"recipient_commitment,omitempty"`
	ChangeCommitment    []byte `protobuf:"bytes,2,opt,name=change_commitment,json=changeCommitment,proto3" json:"change_commitment,omitempty"`
}

func (m *MsgPrivateSendResponse) Reset()         { *m = MsgPrivateSendResponse{} }
func (m *MsgPrivateSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPrivateSendResponse) ProtoMessage()    {}
func (*MsgPrivateSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{3}
}
func (m *MsgPrivateSendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPrivateSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPrivateSendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPrivateSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPrivateSendResponse.Merge(m, src)
}
func (m *MsgPrivateSendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPrivateSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPrivateSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPrivateSendResponse proto.InternalMessageInfo

func (m *MsgPrivateSendResponse) GetRecipientCommitment() []byte {
	if m != nil {
		return m.RecipientCommitment
	}
	return nil
}

func (m *MsgPrivateSendResponse) GetChangeCommitment() []byte {
	if m != nil {
		return m.ChangeCommitment
	}
	return nil
}

// MsgWithdrawFromCommitment withdraws tokens from a commitment
type MsgWithdrawFromCommitment struct {
	Sender            string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId            uint64 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Commitment        []byte `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	RecipientAddress  string `protobuf:"bytes,4,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	WithdrawalAmount  uint64 `protobuf:"varint,5,opt,name=withdrawal_amount,json=withdrawalAmount,proto3" json:"withdrawal_amount,omitempty"`
	Salt              []byte `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	RecipientIdentity []byte `protobuf:"bytes,7,opt,name=recipient_identity,json=recipientIdentity,proto3" json:"recipient_identity,omitempty"`
	Proof             []byte `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
	Nullifier         []byte `protobuf:"bytes,9,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
}

func (m *MsgWithdrawFromCommitment) Reset()         { *m = MsgWithdrawFromCommitment{} }
func (m *MsgWithdrawFromCommitment) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFromCommitment) ProtoMessage()    {}
func (*MsgWithdrawFromCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{4}
}
func (m *MsgWithdrawFromCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawFromCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawFromCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawFromCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFromCommitment.Merge(m, src)
}
func (m *MsgWithdrawFromCommitment) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawFromCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFromCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFromCommitment proto.InternalMessageInfo

func (m *MsgWithdrawFromCommitment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgWithdrawFromCommitment) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *MsgWithdrawFromCommitment) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *MsgWithdrawFromCommitment) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *MsgWithdrawFromCommitment) GetWithdrawalAmount() uint64 {
	if m != nil {
		return m.WithdrawalAmount
	}
	return 0
}

func (m *MsgWithdrawFromCommitment) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *MsgWithdrawFromCommitment) GetRecipientIdentity() []byte {
	if m != nil {
		return m.RecipientIdentity
	}
	return nil
}

func (m *MsgWithdrawFromCommitment) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgWithdrawFromCommitment) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

type MsgWithdrawFromCommitmentResponse struct {
}

func (m *MsgWithdrawFromCommitmentResponse) Reset()         { *m = MsgWithdrawFromCommitmentResponse{} }
func (m *MsgWithdrawFromCommitmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawFromCommitmentResponse) ProtoMessage()    {}
func (*MsgWithdrawFromCommitmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{5}
}
func (m *MsgWithdrawFromCommitmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawFromCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawFromCommitmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawFromCommitmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawFromCommitmentResponse.Merge(m, src)
}
func (m *MsgWithdrawFromCommitmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawFromCommitmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawFromCommitmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawFromCommitmentResponse proto.InternalMessageInfo

// MsgSetVerificationKey sets a verification key for a given circuit type and depth
// This message should be submitted via governance
type MsgSetVerificationKey struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// CircuitType: "deposit", "private_send", or "withdrawal"
	CircuitType string `protobuf:"bytes,2,opt,name=circuit_type,json=circuitType,proto3" json:"circuit_type,omitempty"`
	// MerkleDepth: depth of Merkle tree (only used for private_send circuit)
	MerkleDepth uint32 `protobuf:"varint,3,opt,name=merkle_depth,json=merkleDepth,proto3" json:"merkle_depth,omitempty"`
	// VerificationKey: serialized verification key bytes
	VerificationKey []byte `protobuf:"bytes,4,opt,name=verification_key,json=verificationKey,proto3" json:"verification_key,omitempty"`
}

func (m *MsgSetVerificationKey) Reset()         { *m = MsgSetVerificationKey{} }
func (m *MsgSetVerificationKey) String() string { return proto.CompactTextString(m) }
func (*MsgSetVerificationKey) ProtoMessage()    {}
func (*MsgSetVerificationKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{6}
}
func (m *MsgSetVerificationKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetVerificationKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetVerificationKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetVerificationKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetVerificationKey.Merge(m, src)
}
func (m *MsgSetVerificationKey) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetVerificationKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetVerificationKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetVerificationKey proto.InternalMessageInfo

func (m *MsgSetVerificationKey) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetVerificationKey) GetCircuitType() string {
	if m != nil {
		return m.CircuitType
	}
	return ""
}

func (m *MsgSetVerificationKey) GetMerkleDepth() uint32 {
	if m != nil {
		return m.MerkleDepth
	}
	return 0
}

func (m *MsgSetVerificationKey) GetVerificationKey() []byte {
	if m != nil {
		return m.VerificationKey
	}
	return nil
}

type MsgSetVerificationKeyResponse struct {
}

func (m *MsgSetVerificationKeyResponse) Reset()         { *m = MsgSetVerificationKeyResponse{} }
func (m *MsgSetVerificationKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetVerificationKeyResponse) ProtoMessage()    {}
func (*MsgSetVerificationKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddd6ca3aae8b291, []int{7}
}
func (m *MsgSetVerificationKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetVerificationKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetVerificationKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetVerificationKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetVerificationKeyResponse.Merge(m, src)
}
func (m *MsgSetVerificationKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetVerificationKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetVerificationKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetVerificationKeyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgDepositToShielded)(nil), "evmos.shielded.v1.MsgDepositToShielded")
	proto.RegisterType((*MsgDepositToShieldedResponse)(nil), "evmos.shielded.v1.MsgDepositToShieldedResponse")
	proto.RegisterType((*MsgPrivateSend)(nil), "evmos.shielded.v1.MsgPrivateSend")
	proto.RegisterType((*MsgPrivateSendResponse)(nil), "evmos.shielded.v1.MsgPrivateSendResponse")
	proto.RegisterType((*MsgWithdrawFromCommitment)(nil), "evmos.shielded.v1.MsgWithdrawFromCommitment")
	proto.RegisterType((*MsgWithdrawFromCommitmentResponse)(nil), "evmos.shielded.v1.MsgWithdrawFromCommitmentResponse")
	proto.RegisterType((*MsgSetVerificationKey)(nil), "evmos.shielded.v1.MsgSetVerificationKey")
	proto.RegisterType((*MsgSetVerificationKeyResponse)(nil), "evmos.shielded.v1.MsgSetVerificationKeyResponse")
}

func init() { proto.RegisterFile("evmos/shielded/v1/tx.proto", fileDescriptor_bddd6ca3aae8b291) }

var fileDescriptor_bddd6ca3aae8b291 = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x4e, 0xdb, 0x4c,
	0x1c, 0xc5, 0x09, 0x09, 0x5f, 0x26, 0x10, 0x12, 0x7f, 0x29, 0xa4, 0x16, 0x35, 0x21, 0x5d, 0x10,
	0xa0, 0x8d, 0x09, 0xed, 0x8a, 0x45, 0x25, 0x5a, 0x5a, 0x09, 0x55, 0x91, 0x90, 0x83, 0x5a, 0xa9,
	0x5d, 0x58, 0x8e, 0x3d, 0xd8, 0x23, 0x62, 0x8f, 0xe5, 0x99, 0x18, 0x82, 0xba, 0xa8, 0x7a, 0x82,
	0x9e, 0xa1, 0x27, 0x60, 0xd5, 0x33, 0xa0, 0xae, 0x58, 0x55, 0x5d, 0x56, 0xb0, 0xe0, 0x1a, 0x95,
	0x3d, 0x8e, 0xed, 0x10, 0xa3, 0x42, 0x37, 0x96, 0xe7, 0xfd, 0xde, 0xcc, 0xfb, 0xfd, 0x9d, 0x01,
	0x02, 0xf4, 0x2c, 0x4c, 0x24, 0x62, 0x22, 0xd8, 0xd7, 0xa1, 0x2e, 0x79, 0x6d, 0x89, 0x9e, 0xb4,
	0x1c, 0x17, 0x53, 0xcc, 0x57, 0x02, 0x5b, 0x6b, 0x64, 0x6b, 0x79, 0x6d, 0x41, 0xd4, 0x30, 0xf1,
	0xf9, 0x3d, 0x95, 0x40, 0xc9, 0x6b, 0xf7, 0x20, 0x55, 0xdb, 0x92, 0x86, 0x91, 0xcd, 0xb6, 0x08,
	0x55, 0x03, 0x1b, 0x38, 0xf8, 0x95, 0xfc, 0xbf, 0x10, 0x5d, 0x0c, 0x77, 0x59, 0xc4, 0xf0, 0x05,
	0x2c, 0x62, 0x30, 0x43, 0xe3, 0x1b, 0x07, 0xaa, 0x1d, 0x62, 0xec, 0x42, 0x07, 0x13, 0x44, 0x0f,
	0x70, 0x37, 0x94, 0xe2, 0x17, 0x40, 0x9e, 0x40, 0x5b, 0x87, 0x6e, 0x8d, 0xab, 0x73, 0xcd, 0x82,
	0x1c, 0xae, 0xf8, 0x45, 0x30, 0xe3, 0x60, 0xdc, 0x57, 0x90, 0x5e, 0xcb, 0xd4, 0xb9, 0xe6, 0xb4,
	0x9c, 0xf7, 0x97, 0x7b, 0xc1, 0x06, 0xd5, 0xc2, 0x03, 0x9b, 0xd6, 0xb2, 0x0c, 0x67, 0x2b, 0x5e,
	0x04, 0x40, 0xc3, 0x96, 0x85, 0xa8, 0x05, 0x6d, 0x5a, 0x9b, 0xae, 0x73, 0xcd, 0x59, 0x39, 0x81,
	0xf0, 0x55, 0x90, 0x73, 0x5c, 0x8c, 0x0f, 0x6b, 0xb9, 0xc0, 0xc4, 0x16, 0xdb, 0xc5, 0x2f, 0xd7,
	0x67, 0xeb, 0xa1, 0x66, 0xe3, 0x05, 0x58, 0x4a, 0xf3, 0x51, 0x86, 0xc4, 0xc1, 0x36, 0x81, 0x37,
	0x24, 0xb8, 0x9b, 0x12, 0x8d, 0x9f, 0x19, 0x50, 0xea, 0x10, 0x63, 0xdf, 0x45, 0x9e, 0x4a, 0x61,
	0x17, 0xda, 0xff, 0x10, 0xde, 0x12, 0x28, 0xd8, 0x83, 0x7e, 0x1f, 0x1d, 0x22, 0xe8, 0x06, 0x11,
	0xce, 0xca, 0x31, 0xc0, 0xaf, 0x82, 0x79, 0x76, 0x80, 0x82, 0x74, 0x68, 0x53, 0x44, 0x87, 0x61,
	0xa4, 0x25, 0x06, 0xef, 0x85, 0x28, 0xdf, 0x06, 0x55, 0x17, 0x6a, 0xc8, 0x41, 0xd0, 0xa6, 0x4a,
	0xc2, 0x69, 0x16, 0xfc, 0xff, 0x91, 0xed, 0x55, 0x9c, 0xa0, 0x0d, 0x50, 0xd1, 0x4c, 0xd5, 0x36,
	0x60, 0x92, 0x9f, 0x0f, 0xf8, 0x65, 0x66, 0x48, 0x90, 0x97, 0x41, 0xd1, 0x82, 0xee, 0x51, 0x1f,
	0x2a, 0x2e, 0xc6, 0xb4, 0x36, 0xc3, 0x72, 0xc1, 0x20, 0x19, 0xe3, 0x44, 0xba, 0xff, 0x4b, 0xa4,
	0x9b, 0x6f, 0x82, 0x72, 0xb8, 0xcd, 0x51, 0xa9, 0xa9, 0x10, 0x74, 0x0a, 0x6b, 0x85, 0x3a, 0xd7,
	0x9c, 0x93, 0x4b, 0x0c, 0xdf, 0x57, 0xa9, 0xd9, 0x45, 0xa7, 0x70, 0xbc, 0x30, 0x27, 0x60, 0x61,
	0x3c, 0xaf, 0x51, 0x49, 0x6e, 0x8b, 0x93, 0xbb, 0x67, 0x9c, 0x99, 0xf4, 0x38, 0x1b, 0x3f, 0x32,
	0xe0, 0x61, 0x87, 0x18, 0xef, 0x11, 0x35, 0x75, 0x57, 0x3d, 0x7e, 0xe3, 0x62, 0x2b, 0x71, 0xd4,
	0xbd, 0xab, 0x3b, 0xde, 0x41, 0xd9, 0x89, 0x26, 0xdd, 0x00, 0x95, 0x38, 0x1c, 0x55, 0xd7, 0x5d,
	0x48, 0x48, 0x50, 0xe1, 0x82, 0x5c, 0x8e, 0x0c, 0x3b, 0x0c, 0xf7, 0xc9, 0xc7, 0xa1, 0x5f, 0x6a,
	0x5f, 0x09, 0x87, 0x22, 0x17, 0xe8, 0x95, 0x63, 0xc3, 0x0e, 0x1b, 0x0f, 0x1e, 0x4c, 0x13, 0xb5,
	0x3f, 0x2a, 0x68, 0xf0, 0xcf, 0x3f, 0x05, 0x7c, 0xac, 0x16, 0x35, 0x14, 0xab, 0x65, 0xec, 0x47,
	0xd4, 0x53, 0xe9, 0x25, 0x1d, 0x6b, 0xd8, 0xc2, 0x8d, 0x86, 0x1d, 0x2f, 0xe3, 0x63, 0xb0, 0x72,
	0x6b, 0x2e, 0x47, 0x15, 0x6d, 0x7c, 0xe7, 0xc0, 0x83, 0x0e, 0x31, 0xba, 0x90, 0xbe, 0x83, 0x2e,
	0x3a, 0x44, 0x9a, 0x4a, 0x11, 0xb6, 0xdf, 0xc2, 0xa1, 0xaf, 0xa4, 0x0e, 0xa8, 0x89, 0x5d, 0xdf,
	0x4b, 0x96, 0xf0, 0x18, 0xe0, 0x57, 0xc0, 0xac, 0x86, 0x5c, 0x6d, 0x80, 0xa8, 0x42, 0x87, 0x0e,
	0x0c, 0x12, 0x5f, 0x90, 0x8b, 0x21, 0x76, 0x30, 0x74, 0xa0, 0x4f, 0x09, 0xbb, 0x4f, 0x87, 0x0e,
	0x35, 0x83, 0xfc, 0xcf, 0xc9, 0x61, 0x23, 0xef, 0xfa, 0x10, 0xbf, 0x06, 0xca, 0x5e, 0x42, 0x56,
	0x39, 0x82, 0xa3, 0x09, 0x9b, 0xf7, 0xc6, 0xdd, 0xd9, 0x2e, 0xf9, 0xa1, 0xc5, 0x0e, 0x34, 0x96,
	0xc1, 0xa3, 0x54, 0xbf, 0x47, 0x91, 0x6d, 0x9d, 0x67, 0x41, 0xb6, 0x43, 0x0c, 0xde, 0x02, 0x95,
	0xc9, 0x7b, 0x70, 0xb5, 0x35, 0x71, 0x07, 0xb7, 0xd2, 0x2e, 0x23, 0x41, 0xba, 0x23, 0x31, 0x1a,
	0x91, 0x8f, 0xa0, 0x98, 0xbc, 0x91, 0x56, 0xd2, 0xf7, 0x27, 0x28, 0xc2, 0xda, 0x5f, 0x29, 0xd1,
	0xe1, 0x9f, 0xc0, 0xc2, 0x2d, 0xb3, 0xf1, 0x24, 0xfd, 0x90, 0x74, 0xb6, 0xf0, 0xfc, 0x3e, 0xec,
	0x48, 0xdd, 0x01, 0x7c, 0x4a, 0x9f, 0x34, 0xd3, 0xcf, 0x9a, 0x64, 0x0a, 0x9b, 0x77, 0x65, 0x8e,
	0x14, 0x85, 0xdc, 0xe7, 0xeb, 0xb3, 0x75, 0xee, 0xe5, 0xeb, 0xf3, 0x4b, 0x91, 0xbb, 0xb8, 0x14,
	0xb9, 0xdf, 0x97, 0x22, 0xf7, 0xf5, 0x4a, 0x9c, 0xba, 0xb8, 0x12, 0xa7, 0x7e, 0x5d, 0x89, 0x53,
	0x1f, 0x36, 0x0c, 0x44, 0xcd, 0x41, 0xaf, 0xa5, 0x61, 0x4b, 0x62, 0x2f, 0x2e, 0xfb, 0x7a, 0x5b,
	0x9b, 0xd2, 0x49, 0xfc, 0xfa, 0xfa, 0x2d, 0x4a, 0x7a, 0xf9, 0xe0, 0x71, 0x7c, 0xf6, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x2a, 0x1e, 0x4d, 0xcf, 0x9c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	DepositToShielded(ctx context.Context, in *MsgDepositToShielded, opts ...grpc.CallOption) (*MsgDepositToShieldedResponse, error)
	PrivateSend(ctx context.Context, in *MsgPrivateSend, opts ...grpc.CallOption) (*MsgPrivateSendResponse, error)
	WithdrawFromCommitment(ctx context.Context, in *MsgWithdrawFromCommitment, opts ...grpc.CallOption) (*MsgWithdrawFromCommitmentResponse, error)
	SetVerificationKey(ctx context.Context, in *MsgSetVerificationKey, opts ...grpc.CallOption) (*MsgSetVerificationKeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) DepositToShielded(ctx context.Context, in *MsgDepositToShielded, opts ...grpc.CallOption) (*MsgDepositToShieldedResponse, error) {
	out := new(MsgDepositToShieldedResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Msg/DepositToShielded", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PrivateSend(ctx context.Context, in *MsgPrivateSend, opts ...grpc.CallOption) (*MsgPrivateSendResponse, error) {
	out := new(MsgPrivateSendResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Msg/PrivateSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawFromCommitment(ctx context.Context, in *MsgWithdrawFromCommitment, opts ...grpc.CallOption) (*MsgWithdrawFromCommitmentResponse, error) {
	out := new(MsgWithdrawFromCommitmentResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Msg/WithdrawFromCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetVerificationKey(ctx context.Context, in *MsgSetVerificationKey, opts ...grpc.CallOption) (*MsgSetVerificationKeyResponse, error) {
	out := new(MsgSetVerificationKeyResponse)
	err := c.cc.Invoke(ctx, "/evmos.shielded.v1.Msg/SetVerificationKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	DepositToShielded(context.Context, *MsgDepositToShielded) (*MsgDepositToShieldedResponse, error)
	PrivateSend(context.Context, *MsgPrivateSend) (*MsgPrivateSendResponse, error)
	WithdrawFromCommitment(context.Context, *MsgWithdrawFromCommitment) (*MsgWithdrawFromCommitmentResponse, error)
	SetVerificationKey(context.Context, *MsgSetVerificationKey) (*MsgSetVerificationKeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) DepositToShielded(ctx context.Context, req *MsgDepositToShielded) (*MsgDepositToShieldedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositToShielded not implemented")
}
func (*UnimplementedMsgServer) PrivateSend(ctx context.Context, req *MsgPrivateSend) (*MsgPrivateSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateSend not implemented")
}
func (*UnimplementedMsgServer) WithdrawFromCommitment(ctx context.Context, req *MsgWithdrawFromCommitment) (*MsgWithdrawFromCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawFromCommitment not implemented")
}
func (*UnimplementedMsgServer) SetVerificationKey(ctx context.Context, req *MsgSetVerificationKey) (*MsgSetVerificationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVerificationKey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_DepositToShielded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDepositToShielded)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DepositToShielded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Msg/DepositToShielded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DepositToShielded(ctx, req.(*MsgDepositToShielded))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PrivateSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPrivateSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PrivateSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Msg/PrivateSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PrivateSend(ctx, req.(*MsgPrivateSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawFromCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawFromCommitment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawFromCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Msg/WithdrawFromCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawFromCommitment(ctx, req.(*MsgWithdrawFromCommitment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetVerificationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetVerificationKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetVerificationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.shielded.v1.Msg/SetVerificationKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetVerificationKey(ctx, req.(*MsgSetVerificationKey))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.shielded.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositToShielded",
			Handler:    _Msg_DepositToShielded_Handler,
		},
		{
			MethodName: "PrivateSend",
			Handler:    _Msg_PrivateSend_Handler,
		},
		{
			MethodName: "WithdrawFromCommitment",
			Handler:    _Msg_WithdrawFromCommitment_Handler,
		},
		{
			MethodName: "SetVerificationKey",
			Handler:    _Msg_SetVerificationKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evmos/shielded/v1/tx.proto",
}

func (m *MsgDepositToShielded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToShielded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToShielded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if m.PoolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDepositToShieldedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDepositToShieldedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDepositToShieldedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPrivateSend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPrivateSend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPrivateSend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MerklePathSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MerklePathSize))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ChangeCommitment) > 0 {
		i -= len(m.ChangeCommitment)
		copy(dAtA[i:], m.ChangeCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChangeCommitment)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RecipientCommitment) > 0 {
		i -= len(m.RecipientCommitment)
		copy(dAtA[i:], m.RecipientCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RecipientCommitment)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SenderIdentity) > 0 {
		i -= len(m.SenderIdentity)
		copy(dAtA[i:], m.SenderIdentity)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SenderIdentity)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPrivateSendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPrivateSendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPrivateSendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChangeCommitment) > 0 {
		i -= len(m.ChangeCommitment)
		copy(dAtA[i:], m.ChangeCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChangeCommitment)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RecipientCommitment) > 0 {
		i -= len(m.RecipientCommitment)
		copy(dAtA[i:], m.RecipientCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RecipientCommitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawFromCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawFromCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawFromCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RecipientIdentity) > 0 {
		i -= len(m.RecipientIdentity)
		copy(dAtA[i:], m.RecipientIdentity)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RecipientIdentity)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x32
	}
	if m.WithdrawalAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalAmount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RecipientAddress) > 0 {
		i -= len(m.RecipientAddress)
		copy(dAtA[i:], m.RecipientAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RecipientAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawFromCommitmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawFromCommitmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawFromCommitmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetVerificationKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetVerificationKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetVerificationKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationKey) > 0 {
		i -= len(m.VerificationKey)
		copy(dAtA[i:], m.VerificationKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerificationKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.MerkleDepth != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MerkleDepth))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CircuitType) > 0 {
		i -= len(m.CircuitType)
		copy(dAtA[i:], m.CircuitType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CircuitType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetVerificationKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetVerificationKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetVerificationKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDepositToShielded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovTx(uint64(m.PoolId))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDepositToShieldedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPrivateSend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovTx(uint64(m.PoolId))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SenderIdentity)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RecipientCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChangeCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MerklePathSize != 0 {
		n += 1 + sovTx(uint64(m.MerklePathSize))
	}
	return n
}

func (m *MsgPrivateSendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecipientCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChangeCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawFromCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovTx(uint64(m.PoolId))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RecipientAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WithdrawalAmount != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalAmount))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RecipientIdentity)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawFromCommitmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetVerificationKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CircuitType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MerkleDepth != 0 {
		n += 1 + sovTx(uint64(m.MerkleDepth))
	}
	l = len(m.VerificationKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetVerificationKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDepositToShielded) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToShielded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToShielded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDepositToShieldedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDepositToShieldedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDepositToShieldedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPrivateSend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPrivateSend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPrivateSend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderIdentity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderIdentity = append(m.SenderIdentity[:0], dAtA[iNdEx:postIndex]...)
			if m.SenderIdentity == nil {
				m.SenderIdentity = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientCommitment = append(m.RecipientCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.RecipientCommitment == nil {
				m.RecipientCommitment = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChangeCommitment = append(m.ChangeCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.ChangeCommitment == nil {
				m.ChangeCommitment = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerklePathSize", wireType)
			}
			m.MerklePathSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MerklePathSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPrivateSendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPrivateSendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPrivateSendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientCommitment = append(m.RecipientCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.RecipientCommitment == nil {
				m.RecipientCommitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChangeCommitment = append(m.ChangeCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.ChangeCommitment == nil {
				m.ChangeCommitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawFromCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawFromCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawFromCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalAmount", wireType)
			}
			m.WithdrawalAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientIdentity", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientIdentity = append(m.RecipientIdentity[:0], dAtA[iNdEx:postIndex]...)
			if m.RecipientIdentity == nil {
				m.RecipientIdentity = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawFromCommitmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawFromCommitmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawFromCommitmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetVerificationKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetVerificationKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetVerificationKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleDepth", wireType)
			}
			m.MerkleDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MerkleDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationKey = append(m.VerificationKey[:0], dAtA[iNdEx:postIndex]...)
			if m.VerificationKey == nil {
				m.VerificationKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetVerificationKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetVerificationKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetVerificationKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
